# Generated by Django 4.2.5 on 2023-10-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True)),
                ("dni", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=75)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=60)),
                ("province", models.CharField(max_length=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True)),
                ("number", models.IntegerField()),
                ("security_code", models.SmallIntegerField()),
                ("expiration_date", models.DateField()),
                ("bank", models.CharField(blank=True, max_length=50, null=True)),
                ("franchise", models.CharField(max_length=30)),
                ("owner_full_name", models.CharField(max_length=60)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.client"
                    ),
                ),
            ],
        ),
    ]
